In [2]:
# Imports
import time
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# PyTorch libraries
import torch
from torch import nn
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor

In [3]:
a = torch.tensor([0,1,2])

b = ((1,2),(3,4),(5,6))
b = torch.tensor(b)

c = np.ones([3,3])
c = torch.tensor(c)


for x in [a,b,c]:
    print ("tensor :", x,"\n")

tensor : tensor([0, 1, 2]) 

tensor : tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

tensor : tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 



In [4]:
"""Notice that .empty() does not return zeros, but seemingly random numbers. Unlike .zeros(), which initialises 
the elements of the tensor with zeros, .empty() just allocates the memory. 
It is hence a bit faster if you are looking to just create a tensor."""
x = torch.ones(3,3,3)
y = torch.zeros(2,2,2)
z = torch.empty(1)
print(x)
print(y)
print(z)


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([0.])


In [5]:
def checkExercise1(A, B, C, D):
  """
  Helper function for checking Exercise 1.

  Args:
    A: torch.Tensor
      Torch Tensor of shape (20, 21) consisting of ones.
    B: torch.Tensor
      Torch Tensor of size([3,4])
    C: torch.Tensor
      Torch Tensor of size([20,21])
    D: torch.Tensor
      Torch Tensor of size([19])

  Returns:
    Nothing.
  """
  assert torch.equal(A.to(int),torch.ones(20, 21).to(int)), "Got: {A} \n Expected: {torch.ones(20, 21)} (shape: {torch.ones(20, 21).shape})"
  assert np.array_equal(B.numpy(),np.vander([1, 2, 3], 4)), "Got: {B} \n Expected: {np.vander([1, 2, 3], 4)} (shape: {np.vander([1, 2, 3], 4).shape})"
  assert C.shape == (20, 21), "Got: {C} \n Expected (shape: {(20, 21)})"
  assert torch.equal(D, torch.arange(4, 41, step=2)), "Got {D} \n Expected: {torch.arange(4, 41, step=2)} (shape: {torch.arange(4, 41, step=2).shape})"
  print("All correct")

In [6]:
def tensor_creation(Z):
  """
  A function that creates various tensors.

  Args:
    Z: numpy.ndarray
      An array of shape (3,4)

  Returns:
    A : Tensor
      20 by 21 tensor consisting of ones
    B : Tensor
      A tensor with elements equal to the elements of numpy array Z
    C : Tensor
      A tensor with the same number of elements as A but with values ∼U(0,1)
    D : Tensor
      A 1D tensor containing the even numbers between 4 and 40 inclusive.
  """
  #################################################
  # ## TODO for students: fill in the missing code
  # ## from the first expression
  # raise NotImplementedError("Student exercise: say what they should have done")
  #################################################
  A = torch.ones(20,21)
  B = torch.tensor(Z)
  C = torch.rand_like(A)
  D = torch.arange(4,41,step=2)

  return A, B, C, D


# numpy array to copy later
Z = np.vander([1, 2, 3], 4)

# Uncomment below to check your function!
A, B, C, D = tensor_creation(Z)
checkExercise1(A, B, C, D)

All correct


In [7]:
print(torch.tensor(np.vander([1, 2, 3], 4)))

tensor([[ 1,  1,  1,  1],
        [ 8,  4,  2,  1],
        [27,  9,  3,  1]])


In [8]:
B = torch.ones(3,1,4)
print(B)

tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]])
